### ISSUE TITLE
Issues with spaces in folder names

### ISSUE THREAD

**Issue by codingmanu** [ribtoks/tdg-github-action#2]
Hi! Thanks for this GH Action!

I'm having a small issue. When I have a space in a folder name inside my project structure, It breaks the hyperlink in the issue. Not sure if this is a GH link parsing problem or if something can be done in the Action to fix this. Maybe quote the link or something like that. Sorry if this is something pretty evident, I'm really new into the GH Actions environment.

Thanks!

![Screen Shot 2020-08-11 at 11 23 31 AM](https://user-images.githubusercontent.com/6534819/89916392-87b44500-dbc5-11ea-9faf-6bc16f097034.png)

**Comment by codingmanu** [comment]
Quoting the whole URL doesn't work, but replacing the spaces with `%20` does. 

![Screen Shot 2020-08-11 at 11 35 45 AM](https://user-images.githubusercontent.com/6534819/89917559-ef1ec480-dbc6-11ea-910d-533f4e0aa94c.png)

**Comment by codingmanu** [comment]
I just realized this might be an issue with the generator library (https://github.com/ribtoks/tdg). Let me know if you'd rather have me put the issue there instead of here.

Thanks!

**Comment by ribtoks** [comment]
Hi

Thanks for reporting this problem.

You created an issue in correct repository, the bug is in this function https://github.com/ribtoks/tdg-github-action/blob/master/main.go#L205

I'll try to fix it later.

**Comment by ribtoks** [comment]
@codingmanu Please check master to see if it works for you. If it is fixed for you, I'll create a new release

**Comment by codingmanu** [comment]
Works perfect, thanks!
