### ISSUE TITLE
EXCLUDE_PATTERN regex doesn't work.

### ISSUE THREAD

**Issue by sammcj** [ribtoks/tdg-github-action#22]
It looks like EXCLUDE_PATTERN doesn't seem to work properly.

```
EXCLUDE_PATTERN: ".*.\/(node_modules|dist|bin|files|themes)\/.*"
```

This is a valid regex that should match any exactly named directory.

![image](https://user-images.githubusercontent.com/862951/209019769-37faee92-4719-4a2d-9d26-944d429b17cf.png)

However - it doesn't seem to filter anything out - you still get issues logged for files such as:

```
./files/somefile.txt
./themes/some/thing.txt
./themes/mytheme/node_modules/something.js
```

etc...

Somewhat related - would it also be better to accept a list/array of files/patterns to match on?, e.g:

```yaml
exclude:
  - "./node_modules/*"
  - ".*/files/somefile"
  - ".*/**/bacon.yu*"
```

or if it has to be a string:

```yaml
exclude: |
  "./node_modules/*"
  ".*/files/somefile"
  ".*/**/bacon.yu*"
```

**Comment by ribtoks** [comment]
Hi

Thank you for reporting this issue. To make it work, please remove `./` (current directory) from your desired match string.

The underlying library tdg supports an array of exclude patterns already [here](https://github.com/ribtoks/tdg-github-action/blob/80cb94c6b2373307f8a99fdf0ac6c4ea9192e394/main.go#L452). So the remaining part would be only to have it in `.yml` if you would like to work on this.

**Comment by sammcj** [comment]
Oh that's very helpful, thank you so much - I think that's done it!
