### ISSUE TITLE
Close issue with comment/reason

### ISSUE THREAD

**Issue by snebjorn** [ribtoks/tdg-github-action#4]
I was wondering if it's possible for this tool to close issues with a comment from the commit message.

Example TODO comment
```
//TODO are we sure the below is correct?
var foo = bar;
```
Then someone could close it with this commit
```diff
-//TODO are we sure the below is correct?
var foo = bar;
```
> answered TODO
> Yes it's correct because lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Not sure if the commit message itself as the comment on the issue would be desired. In that case some kind of keyword could be used, like `closingComment=`.
That would make the above look like
> answered TODO
> closingComment=Yes it's correct because lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by ribtoks** [comment]
Hi @snebjorn 

Currently this is not supported, but I like the idea. If you want to start working on it and you have any question on tdg, please let me know

**Comment by snebjorn** [comment]
Cool :)

I can't promise anything. I might get hit by sudden wave of productivity 🚀 or I might get lost in an endless youtube spiral ☠️. I'd say there's a 50/50 chance 🤡
