### ISSUE TITLE
Support TODOs in Twig Comments

### ISSUE THREAD

**Issue by cadonau** [ribtoks/tdg-github-action#41]
I’m not sure if it’s somehow already possible to have this workflow add issues for TODO [comments in Twig files](https://twig.symfony.com/doc/3.x/templates.html#comments). Or whether the feature request should more appropriately be placed elsewhere: https://gitlab.com/ribtoks/tdg/-/issues

**Comment by ribtoks** [comment]
Hi. Yes, if the `tdg` will parse this (you found a correct repository), than `tdg-github-action` will do it automatically. So that reporisitory is a correct place for this issue.

**Comment by cadonau** [comment]
@ribtoks Thank you! I opened [an issue there](https://gitlab.com/ribtoks/tdg/-/issues/9).
