### ISSUE TITLE
[IMPROVEMENT] Make the action faster

### ISSUE THREAD

**Issue by aditya-mitra** [ribtoks/tdg-github-action#5]
Currently the actions is taking around **30s** for build.
Is there a way you can cache it or reduce the seconds?

![image](https://user-images.githubusercontent.com/55396651/116401866-5bbb1b80-a849-11eb-98ed-fa3a58d0de0f.png)

**Comment by ribtoks** [comment]
Hi @aditya-mitra . I think 30 seconds is not too much.

**Comment by aditya-mitra** [comment]
Yeah, you are right.
But, I think if it could be improved, it would be great enhancement (the whole workflow would be finished in 10s or less). You can also see the main action `(Add/Remove Todos`) is very fast
