### ISSUE TITLE
exclude `.git` by default

### ISSUE THREAD

**Issue by njzjz** [ribtoks/tdg-github-action#69]
TODO tags in the `.git` directory are obviously what we don't want to track...

![image](https://github.com/ribtoks/tdg-github-action/assets/9496702/3225baf9-6cbc-4b5f-842c-1375ea55fcbb)

**Comment by ribtoks** [comment]
Thanks! Fixed in 2ed93d55d413428152ddd318ed8238293765cf6f

**Comment by njzjz** [comment]
It seems to me the `.github` directory was wrongly excluded since it contains a prefix of `.git`...

xref: https://github.com/deepmodeling/deepmd-kit/issues/3520#issuecomment-2007907909

**Comment by ribtoks** [comment]
Good point. Fixed in v0.4.10 of this action.
